version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URI=mongodb://mongo:27017/contactdb
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
